// <auto-generated />
using System;
using ComertApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComertApp.Migrations
{
    [DbContext(typeof(ComertDbContext))]
    partial class ComertDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("ComertApp.Entities.Desfacere", b =>
                {
                    b.Property<int>("IdDesfacere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantitate")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataVanzarii")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRaion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProdusVandut")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valoare")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDesfacere");

                    b.HasIndex("IdRaion");

                    b.ToTable("Desfaceri");
                });

            modelBuilder.Entity("ComertApp.Entities.Magazin", b =>
                {
                    b.Property<int>("IdMagazin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMagazin");

                    b.ToTable("Magazine");
                });

            modelBuilder.Entity("ComertApp.Entities.Raion", b =>
                {
                    b.Property<int>("IdRaion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMagazin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumarAngajati")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdRaion");

                    b.HasIndex("IdMagazin");

                    b.ToTable("Raioane");
                });

            modelBuilder.Entity("ComertApp.Entities.Desfacere", b =>
                {
                    b.HasOne("ComertApp.Entities.Raion", "Raion")
                        .WithMany("Desfaceri")
                        .HasForeignKey("IdRaion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raion");
                });

            modelBuilder.Entity("ComertApp.Entities.Raion", b =>
                {
                    b.HasOne("ComertApp.Entities.Magazin", "Magazin")
                        .WithMany("ListaRaioane")
                        .HasForeignKey("IdMagazin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazin");
                });

            modelBuilder.Entity("ComertApp.Entities.Magazin", b =>
                {
                    b.Navigation("ListaRaioane");
                });

            modelBuilder.Entity("ComertApp.Entities.Raion", b =>
                {
                    b.Navigation("Desfaceri");
                });
#pragma warning restore 612, 618
        }
    }
}
